### ISSUE TITLE
Clarify constraints on Preseed Values

### ISSUE THREAD

**Issue by SteadBytes** [ipxe/cx#6]
**Preseed Value** used for Seed Calculation is [defined](https://github.com/ipxe/cx/blob/master/spec/cx.lyx#L1244) as:
> A sequence of pseudorandom bytes used in conjunction with a **Preseed Verification Key** to construct a **Seed Value**.

Are there any further constraints on the source used to generate this value? e.g. would reading `n` bytes from `/dev/urandom` be sufficient or should a further PRNG be used such as OpenSSL `RAND_bytes`? Are there any potential risks w.r.t seed calculation if Preseed Values are not generated with sufficient randomness?

Context: Deciding where the responsibility lies for generating this value between Android/iOS and a core shared library.

**Comment by mcb30** [comment]
To avoid violating the SP800-90 requirements, it needs to be a source with a security strength at least equal to that of the DRBG, so you need at least a 128-bit security strength to generate a preseed value for a type 1 generator.

It's probably a good idea to add a core C library function to generate a suitable preseed so that, where possible, application developers don't have to think about it.  That said, the documentation for `RAND_DRBG_generate` has some worrying comments about the OpenSSL library implementation not having access to a suitable entropy source.  I'll take a look.

**Comment by SteadBytes** [comment]
Thanks for clarification. Yes I agree, it would be beneficial to remove that decision from higher levels and leave it up to the core library to manage👍

> some worrying comments

Oh dear that's slightly concerning 😅 I imagine that, at the lowest level, OpenSSL can't *guarantee* that the hardware provides a sufficient source of entropy. I guess that we will have assume that the hardware does provide a sufficient source otherwise I'm not sure there's much we can do!

I'll be intrigued to see what you find.👍

**Comment by mcb30** [comment]
It seems as though current (pre-3.0) OpenSSL releases assume that the entropy source may not be a live entropy source, and so refuse to claim the ability to provide prediction resistance.  This was changed in the (unreleased) commit https://github.com/openssl/openssl/commit/65175163247fe0f56c894c9ac7baf93f4386cebe - it is now deemed to be the user's responsibility to ensure that a live entropy source is available.

**Comment by mcb30** [comment]
Having looked for reference at the code used to generate RSA private keys, it ultimately calls `RAND_bytes` (or `RAND_priv_bytes`) which implicitly uses a global DRBG instance with whatever the default security strength happens to be.  This in turn implicitly assumes that the system entropy source (used when a DRBG is instantiated without using `RAND_DRBG_set_callbacks`) is, in some sense, "good enough" for generating private keys.  The default entropy source appears to be `/dev/random`, though it's hard to be certain given the sheer number of `#ifdef`s in the relevant file.

The most conformant approach seems to be to instantiate a single-use DRBG at the required security strength and with no callbacks configured: this will then pull the required amount of entropy from the system entropy source.  This avoids the problem that using `RAND_bytes` implicitly reduces the security strength to whatever happens to be the library default strength.

**Comment by mcb30** [comment]
(Still no guarantee that the entropy source is actually live, but it at least avoids one technical violation of SP800-90.)

**Comment by mcb30** [comment]
I've added `cx_preseed_value` in https://github.com/ipxe/cx/commit/1b1d60ed5520fde8101dccb97b242d685585c77d to generate a preseed value via a single-use DRBG as described above.  Will also add functions for generating a preseed key pair.

As a heads-up: the API for `cx_seedcalc` may change to use an `EVP_PKEY` rather than `X509_PUBKEY`, since most of the OpenSSL APIs seem to prefer passing around `EVP_PKEY` structures.

**Comment by SteadBytes** [comment]
Generating using a single use DRBG seems like a good approach to me 👍 

Is it worth enforcing usage of that by removing the pressed value parameter from the seed generation public API? https://github.com/ipxe/cx/blob/master/c/src/seedcalc.c

**Comment by mcb30** [comment]
> Is it worth enforcing usage of that by removing the pressed value parameter from the seed generation public API? https://github.com/ipxe/cx/blob/master/c/src/seedcalc.c

No, because the Advertiser always needs to know the Preseed Value that it constructed, and the Publisher needs to use the value from the Seed Report.

**Comment by SteadBytes** [comment]
Good point 👍

Is it correct to assume that "psuedorandom" is sufficient description for the specification then? e.g. the reader should ensure that the PRNG used is indeed sufficiently random and correct but other than that there are no further requirements.

**Comment by mcb30** [comment]
The spec wording currently says "An Advertiser MUST construct the Preseed Value using an RBG that is known to have a security strength equal to or greater than the security strength specified for the Generator Type in section 3.1", which I think covers the requirement.

**Comment by mcb30** [comment]
> As a heads-up: the API for `cx_seedcalc` may change to use an `EVP_PKEY` rather than `X509_PUBKEY`, since most of the OpenSSL APIs seem to prefer passing around `EVP_PKEY` structures.

This API change is now done: https://github.com/ipxe/cx/commit/3e14b7adf590d08255bf02e8dd30616ec1fa6985

**Comment by SteadBytes** [comment]
> The spec wording currently says "An Advertiser MUST construct the Preseed Value using an RBG that is known to have a security strength equal to or greater than the security strength specified for the Generator Type in section 3.1", which I think covers the requirement.

Agreed, I shall close this now - thanks! :+1:
